### ISSUE TITLE
Corrected change domain picker for forest roots without children.

### ISSUE THREAD

**Issue by danSpotter** [ITMicaH/Powershell-functions#1]
`$FormEvent_Shown = {
            #Create domains treeview

```
        $parentdomains = $forest.domains | ? {$_.parent -eq $null}

        foreach ($parent in $parentdomains) {

            $DN = $parent.GetDirectoryEntry().distinguishedName

            $rootdomainnode = Add-Node -dname $dn -name $parent.name -RootNode $TreeviewForest -Type Domain

                Get-NextLevel -RootNode $rootdomainnode -Type Domain

        }`
```

**Comment by ITMicaH** [comment]
Sorry for the late response. I'm a bit new to GitHub. Nice catch! Although I'm wondering why anyone would click Change Domain if there's only one domain. Instead of your solution I've disabled the Change Domain option if there's only one domain. I'll upload the change later today. Thanks for bringing this to my attention.

**Comment by danSpotter** [comment]
I do agree on disabling the event for single domains but this solution is for forests where the empty root is side by side. I've worked in two orgs that do it this way.

forestrootdomain.local ..  domain.com >> second.domain.com

**Comment by danSpotter** [comment]
The technical term would be peer-root domain model. Here is an example.

http://programming4.us/desktop/2236.aspx
